# Generated by Django 4.0.4 on 2022-06-24 20:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ItemCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idusuario', models.IntegerField(default=0)),
                ('idcompra', models.IntegerField(default=0)),
                ('nombreProducto', models.CharField(max_length=200)),
                ('precioProducto', models.IntegerField()),
                ('imagenProducto', models.ImageField(null=True, upload_to='items_carrito')),
                ('cantidad', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idusuario', models.IntegerField(default=0)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('total', models.IntegerField(default=0)),
                ('updated_at', models.DateField(auto_now=True)),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.estadocompra')),
            ],
        ),
    ]
