# Generated by Django 4.0.4 on 2022-06-25 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_estadocompra_itemcompra_compra'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoSubscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idusuario', models.IntegerField(default=0)),
                ('monto', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('estado', models.ForeignKey(default='Activo', on_delete=django.db.models.deletion.CASCADE, to='app.estadosubscripcion', to_field='descripcion')),
            ],
        ),
    ]
