# Generated by Django 4.0.4 on 2022-06-26 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_estadosubscripcion_subscripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='descuento',
            field=models.BooleanField(default=False),
        ),
    ]
